# Add host configuration here as a table
# Laboratory will iterate all top-level elements in this file to discover host configurations
# Build-command is performed via a process call into powershell core using the repository root as the working directory
# Executable-path should be the relative path to the host accessible after building

[Alchemist]
enabled = false
build-commands = [
    "dotnet publish Alchemist/Alchemist.csproj --self-contained=false -o Alchemist/Build -v n"
]
executable-path = "Alchemist/Build/Alchemist"

[libelement_cli]
enabled = true
build-commands = [
    "cmake -S ./libelement.CLI -B ./libelement.CLI/build",
    "cmake --build ./libelement.CLI/build --config Release" 
]
executable-path = "libelement.CLI/bin/Release/libelement_cli"