# Add host configuration here as a table
# Laboratory will iterate all top-level elements in this file to discover host configurations
# Build-command is performed via a process call into powershell core using the repository root as the working directory
# Executable-path should be the relative path to the host accessible after building

[Alchemist]
enabled = true
build-command = "dotnet publish Alchemist/Alchemist.csproj --self-contained=false -o Alchemist/Build -v n"
executable-path = "Alchemist/Build/Alchemist"


