name: LMNT

on: [push]

jobs:
  build-lmnt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build
      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE/LMNT -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON
      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config Release
      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest --verbose -C Release
